package com.example.returnmanagement.enums;

public enum ReturnRecordStatus {
	CREATED,
	APPROVED,
	RETURN_IN_TRANSIT,
	RETURN_PARTIALLY_DELIVERED,
	RETURN_DELIVERED,
	REFUND_REQUESTED,
	ZORO_REFUNDED,
	AMAZON_REFUNDED,
	AMAZON_ZORO_REFUNDED,
	REPLACEMENT_REQUESTED,
	REPLACEMENT_CREATED,
	CLOSED
}
